### ISSUE TITLE
Ik heb overflow 

### ISSUE THREAD

**Issue by Sascha-Davidson** [Knetters/server-side-rendering#5]
bekijk de waardens in 
![image](https://user-images.githubusercontent.com/112861160/224290960-774e063a-3951-46ad-a974-44432424bda2.png)
![image](https://user-images.githubusercontent.com/112861160/224290996-e5156ce4-e9bd-43aa-afff-c0c9c428b279.png)

**Comment by Knetters** [comment]
Responsive gemaakt
